device: iPhone 16 Pro Max
osVersion: 18
realMobile: true
browserVersion: latest
resolution: 1179x2556
consoleLogs: info
networkLogs: true
video: true
screenshot: true
selfHeal: true
smartWait: true
debug: true
interactiveDebugging: true
local: false