execution:
  runEnv: qa
  runRemote: true
  device: mobile
  headless: false
project:
  name: Valentino's Magic Beans
  build: Harvest of Quality
azure:
  host: dev.azure.com
  organization: automacoes-qa
  project: automacao