execution:
  runEnv: qa
  runRemote: false
  device: desktop
  headless: false
  percy: false
project:
  name: Valentino's Magic Beans
  build: Harvest of Quality
azure:
  host: dev.azure.com
  organization: automacoes-qa
  project: automacao